version: "3"
services:
  redis:
    image: redis:7.0
    restart: always

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  web:
    image: goropikari/dmoj-site
    container_name: web
    stdin_open: true
    tty: true
    environment:
      - DB_DATABASE=dmoj
      - DB_HOST=db
      - DB_USER=dmoj
      - DB_PASSWORD=password
      - TZ=Asia/Tokyo
      - DEBUG=false # true/false
      - TWO_STEP_REGISTRATION=false # true/false false の場合はメール認証無し
    ports:
      - 8080:80
      - 8000:8000
    volumes:
      - ./problems:/home/ubuntu/problems
    depends_on:
      - db
      - redis

  judger:
    image: goropikari/dmoj-judger
    restart: always
    volumes:
      - ./problems:/home/judge/problems
    tty: true
    cap_add:
      - SYS_PTRACE
    environment:
      - SITE_HOST=web
    depends_on:
      - web
