FROM mcr.microsoft.com/devcontainers/ruby:3.3-bookworm

RUN apt-get update && apt-get install -y \
    libseccomp-dev \
    build-essential \
    python3-dev \
    pipx

USER vscode
RUN pipx install dmoj