#!/bin/bash

docker login
docker push goropikari/dmoj-site:latest
docker push goropikari/dmoj-judger:latest

TAG=$(date "+%Y%m%d-%H%M%S")
docker tag goropikari/dmoj-site:latest goropikari/dmoj-site:${TAG}
docker tag goropikari/dmoj-judger:latest goropikari/dmoj-judger:${TAG}
