#!/bin/bash

docker login
docker push goropikari/dmoj-site:latest

TAG=$(date "+%Y%m%d-%H%M%S")
docker tag goropikari/dmoj-site:latest goropikari/dmoj-site:${TAG}

docker push goropikari/dmoj-site:${TAG}
